package hwforums::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'hwforums::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:hwforums',
        user => 'root',
        password => 'admin',
        AutoCommit => q{1},
    }
);

=head1 NAME

hwforums::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<hwforums>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<hwforums::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Vo Nguyen Hiep

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
